# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00c271734f97fe3ba1f2a2b96e2b561c3bd62ffd753402285dd7e597693b84377ab4523ace933076943aa2b9850980310670d21688357c9572021bae1388132c

test:
  secret_key_base: a11ef3ef2c226841835621e0e4168451d9b4932b6f6a19aab52d2953e5247bf9d0f5294db4e779ccc284ca699e53ebc797fe4bd884a7621c26215b048add6914

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
